//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AudioTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF7FFFD4")]
        public global::System.Windows.Media.Color DocumentStubColor {
            get {
                return ((global::System.Windows.Media.Color)(this["DocumentStubColor"]));
            }
            set {
                this["DocumentStubColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFFE4C4")]
        public global::System.Windows.Media.Color FolderStubColor {
            get {
                return ((global::System.Windows.Media.Color)(this["FolderStubColor"]));
            }
            set {
                this["FolderStubColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF6495ED")]
        public global::System.Windows.Media.Color CueStubColor {
            get {
                return ((global::System.Windows.Media.Color)(this["CueStubColor"]));
            }
            set {
                this["CueStubColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF87CEFA")]
        public global::System.Windows.Media.Color SoundStubColor {
            get {
                return ((global::System.Windows.Media.Color)(this["SoundStubColor"]));
            }
            set {
                this["SoundStubColor"] = value;
            }
        }
    }
}
